server_name: localhost
user_name: admin
repositories:
  ipa325_ur5:
    ros_distro: [groovy]
    robots: null
    jobs: []
    poll: true
    dependencies: {}
    prio_ubuntu_distro: precise
    regular_matrix: {}
    prio_arch: amd64
    type: hg
    url: ssh://jenkinsuser@laotse://var/repos/hg/repos/ipa325_ur5
    version: groovy_dev
email: kevin.broeselge@ipa.fraunhofer.de
committer_email_enabled: false
