server_name: localhost
user_name: admin
repositories:
  cob_common:
    ros_distro: [groovy]
    robots: null
    jobs: []
    poll: true
    dependencies: {}
    prio_ubuntu_distro: oneiric
    regular_matrix: {}
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_common.git
    version: groovy_dev
email: kevin.broeselge@ipa.fraunhofer.de
committer_email_enabled: false
